### ISSUE TITLE
error: unknown type name ‘cusparseHybMat_t’

### ISSUE THREAD

**Issue by ssconquer** [eigs/EVSL#20] opened 2021-05-28 03:02 UTC
I encountered an issue of "error: unknown type name ‘cusparseHybMat_t’ ", when compiling EVSL-1.1.1 with cuda in Ubuntu 20.04.

My approach is as follows:
**1. export CUDA_HOME=/usr/local/cuda-11.2
2. ./configure --with-cuda
3. make**

The detailed output is below:
Making SRC ...
make[1]: Entering directory '/home/lxl/EVSL-master/EVSL_1.1.1/SRC'
gcc -O2 -Wall -Wno-unused-result  -I../INC -I/usr/local/cuda-11.2/include -o cheblanNr.o -c cheblanNr.c
In file included from ../INC/evsl.h:20,
                 from ../INC/internal_header.h:10,
                 from cheblanNr:6:
../INC/struct.h:51:3: error: unknown type name ‘cusparseHybMat_t’
   51 |   cusparseHybMat_t   hyb;
      |   ^~~~~~~~~~~~~~~~
make[1]: *** [../makefile.in:36: cheblanNr] Error 1
make[1]: Leaving directory '/home/lxl/EVSL-master/EVSL_1.1.1/SRC'
make: *** [makefile:18: all] Error 1

Can you help me on this?

**Comment by liruipeng** [comment] 2021-05-31 18:43
@ssconquer The problem is from CUDA 11, `cusparseHybMat_t` is no longer available. I will push changes on this. Meanwhile you can use CUDA 10.1. Thanks!

**Comment by ssconquer** [comment] 2021-06-02 07:53
@liruipeng  Hi,  I tried CUDA 10.1 instead, and ran ./MMPLanN.ex with the default input matrix A.mtx. Lanczos broke down with beta=0. There may be some other bugs when using cuda.

**Comment by liruipeng** [comment] 2021-11-26 05:49
Hi @ssconquer the support for CUDA 11 has been added in #21 . Can you please give it a try and let me if it works for you? Regarding `MMPLanN.ex` with the default matrix `stiff1`, I had no issues running on GPUs, which computed the 1538 eigenvalues. Can you provide more information on the problem you had? Thanks!

**Comment by ssconquer** [comment] 2021-11-29 02:05
Hi, @liruipeng 
I tested the cuda-fix branch in my workstation with cuda-11.2. The problem of MMPLanN.ex remains not solved.
The CPU version computed 1538 eigenvalues which is fine. But the GPU version print lots of warnings, such as "Lucky breakdown, beta = 4.401691731779179e-18", and computed nothing.
I put the testing result here. Hope it helps.

![Screenshot from 2021-11-29 09-54-00](https://user-images.githubusercontent.com/21996931/143797737-0437c2f3-2c9c-4f61-ae91-a24d42e1f064.png)

[MMPLanN_stiff1.txt](https://github.com/eigs/EVSL/files/7614996/MMPLanN_stiff1.txt)

**Comment by liruipeng** [comment] 2021-11-29 16:19
> Hi, @liruipeng I tested the cuda-fix branch in my workstation with cuda-11.2. The problem of MMPLanN.ex remains not solved. The CPU version computed 1538 eigenvalues which is fine. But the GPU version print lots of warnings, such as "Lucky breakdown, beta = 4.401691731779179e-18", and computed nothing. I put the testing result here. Hope it helps.
> 
> ![Screenshot from 2021-11-29 09-54-00](https://user-images.githubusercontent.com/21996931/143797737-0437c2f3-2c9c-4f61-ae91-a24d42e1f064.png)
> 
> [MMPLanN_stiff1.txt](https://github.com/eigs/EVSL/files/7614996/MMPLanN_stiff1.txt)

How did you configure EVSL? Can you try `./configure --with-cuda EVSL_CUDA_SM=75`? Thanks!

**Comment by ssconquer** [comment] 2021-11-30 02:12
@liruipeng I tried "./configure --with-cuda EVSL_CUDA_SM=75", and everything is fine now. MMPLanN.ex computed 1538 eigenvalues for stiff1 matrix. I simply used "./configure --with-cuda" yesterday, by the way. Finally, thank you for your support for CUDA 11!

**Comment by liruipeng** [comment] 2021-11-30 05:13
@ssconquer Thank you! I close this issue now and merge the PR.

**Closed as completed by liruipeng** 2021-11-30 05:13 UTC
